name: Monthly Slate Email

on:
  schedule:
    # 08:37 UTC (9h37 ou 10h37 en France). Décalage pour éviter les embouteillages de GitHub Actions.
    - cron: '37 8 1 * *'
  workflow_dispatch: # Permet de le lancer manuellement depuis l'interface GitHub pour tester

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Run script
        run: node scripts/sendMonthlySlateEmail.js
