name: Weekly Stock Email

on:
  schedule:
    # 17:43 UTC correspond à 18:43 ou 19:43 en France. Évite les embouteillages de l'heure pleine sur GitHub Actions. (Tous les dimanches = 0)
    - cron: '43 17 * * 0'
  workflow_dispatch: # Permet de le lancer manuellement depuis l'interface GitHub

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Run script
        run: node scripts/sendWeeklyStockEmail.js
